name: madsci_example_lab

# * Usage Notes:
# - Environment variables can be set in a `.env` file or directly in the shell.
# - The `REPO_PATH` variable should point to the root of the repository.
# - The `example_lab` directory should contain the lab definition and module files.
# - The `madsci` image is built from the Dockerfile in the current directory.
# - The `madsci_dashboard` image is built from the Dockerfile.dashboard in the current directory.

x-madsci-service: &madsci-service
  image: ghcr.io/ad-sdl/madsci:latest
  build:
    context: .
    dockerfile: Dockerfile
    tags:
      - ghcr.io/ad-sdl/madsci:latest
      - ghcr.io/ad-sdl/madsci:dev
  environment:
    - USER_ID=${USER_ID:-1000}
    - GROUP_ID=${GROUP_ID:-1000}
  network_mode: host
  env_file:
    - .env
  volumes:
    - ${REPO_PATH:-.}/example_lab:/home/madsci/example_lab
    - ${REPO_PATH:-.}/.madsci:/home/madsci/.madsci:rw
    - ${REPO_PATH:-.}/src:/home/madsci/MADSci/src
  entrypoint: ["/bin/bash", "-c", "chmod -R 777 /home/madsci/.madsci 2>/dev/null || true && exec \"$@\"", "--"]
  restart: unless-stopped
  working_dir: /home/madsci/example_lab

services:
  mongodb:
    container_name: mongodb
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ${REPO_PATH:-.}/.madsci/mongodb:/data/db

  redis:
    container_name: redis
    image: redis:7.4
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ${REPO_PATH:-.}/.madsci/redis:/data
    command: redis-server --appendonly yes --save 900 1 --save 300 10 --save 60 10000

  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=madsci
      - POSTGRES_PASSWORD=madsci
      - POSTGRES_DB=resources
    ports:
      - 5432:5432
    volumes:
      - ${REPO_PATH:-.}/.madsci/postgres:/var/lib/postgresql/data

  minio:
    container_name: minio
    image: minio/minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ${REPO_PATH:-.}/.madsci/minio:/home/madsci/.madsci/minio
    command: server /home/madsci/.madsci/minio --console-address ":9001"

  # *Managers
  lab_manager:
    <<: *madsci-service
    container_name: lab_manager
    image: ghcr.io/ad-sdl/madsci_dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile.dashboard
      tags:
        - ghcr.io/ad-sdl/madsci_dashboard:latest
        - ghcr.io/ad-sdl/madsci_dashboard:dev
    command: python -m madsci.squid.lab_server
    depends_on:
      - event_manager
    ports:
      - "8000:8000"



  event_manager:
    <<: *madsci-service
    container_name: event_manager
    command: python -m madsci.event_manager.event_server
    depends_on:
      - mongodb

  experiment_manager:
    <<: *madsci-service
    container_name: experiment_manager
    command: python -m madsci.experiment_manager.experiment_server
    depends_on:
      - mongodb
      - lab_manager

  resource_manager:
    <<: *madsci-service
    container_name: resource_manager
    command: python -m madsci.resource_manager.resource_server
    depends_on:
      - postgres
      - event_manager

  data_manager:
    <<: *madsci-service
    container_name: data_manager
    command: python -m madsci.data_manager.data_server
    depends_on:
      - mongodb
      - event_manager

  location_manager:
    <<: *madsci-service
    container_name: location_manager
    command: python -m madsci.location_manager.location_server
    depends_on:
      - redis
      - event_manager
      - resource_manager

  workcell_manager:
    <<: *madsci-service
    container_name: workcell_manager
    command: python -m madsci.workcell_manager.workcell_server --cold_start_delay 0
    depends_on:
      - redis
      - mongodb
      - resource_manager
      - event_manager
      - postgres
      - location_manager

  # *Nodes
  liquidhandler_1:
    <<: *madsci-service
    container_name: liquidhandler_1
    environment:
      - NODE_DEFINITION=node_definitions/liquidhandler_1.node.yaml
      - NODE_URL=http://localhost:2000
    command: python example_modules/liquidhandler.py

  liquidhandler_2:
    <<: *madsci-service
    container_name: liquidhandler_2
    environment:
      - NODE_DEFINITION=node_definitions/liquidhandler_2.node.yaml
      - NODE_URL=http://localhost:2001
    command: python example_modules/liquidhandler.py

  robotarm_1:
    <<: *madsci-service
    container_name: robotarm_1
    environment:
      - NODE_DEFINITION=node_definitions/robotarm_1.node.yaml
      - NODE_URL=http://localhost:2002
    command: python example_modules/robotarm.py

  platereader_1:
    <<: *madsci-service
    container_name: platereader_1
    environment:
      - NODE_DEFINITION=node_definitions/platereader_1.node.yaml
      - NODE_URL=http://localhost:2003
    command: python example_modules/platereader.py

  advanced_example_node:
    <<: *madsci-service
    container_name: advanced_example_node
    environment:
      - NODE_DEFINITION=node_definitions/advanced_example_node.node.yaml
      - NODE_URL=http://localhost:2004
    command: python example_modules/advanced_example_module.py

<<<<<<< HEAD
  opentrons_1:
    <<: *madsci-service
    container_name: opentrons_1
    environment:
      - NODE_DEFINITION=node_definitions/opentrons_1.node.yaml
      - NODE_URL=http://169.254.19.251:2006
    command: ["python", "/home/madsci/example_lab/example_modules/opentrons.py"]
    depends_on:
      - workcell_manager


=======
  ot2_node:
    image: ghcr.io/ad-sdl/madsci:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/ad-sdl/madsci:latest
        - ghcr.io/ad-sdl/madsci:dev
    container_name: ot2_node
    environment:
      USER_ID: ${USER_ID:-1000}
      GROUP_ID: ${GROUP_ID:-1000}
      NODE_DEFINITION: node_definitions/ot2.node.yaml
      NODE_URL: http://localhost:2010
    env_file:
      - .env
    volumes:
      - ${REPO_PATH:-.}/example_lab:/home/madsci/example_lab
      - ${REPO_PATH:-.}/.madsci:/home/madsci/.madsci:rw
      - ${REPO_PATH:-.}/src:/home/madsci/MADSci/src
    entrypoint: ["/bin/bash", "-c", "chmod -R 777 /home/madsci/.madsci 2>/dev/null || true && exec \"$@\"", "--"]
    restart: unless-stopped
    working_dir: /home/madsci/example_lab
    command: python example_modules/ot2_node.py
    ports:
      - "2010:2010"
>>>>>>> 49fd936d1468dd6a408b22b85e727a4e97e9074e
